import java.util.ArrayList;

public class BookLibrarian {
    private ArrayList<BookInformation> books = new ArrayList<>();
    private BookSorter sort = new DefaultSort();

    public BookLibrarian() {
        // here we go
        // @formatter:off
        books.add(new BookInformation("Muhammad Vandestra", 2017, "Islam Folklore Prophet Jesus (Isa) Son of Mary & The Bird from Clay", "In the beginning I was clay then I became a bird by Allah's leave. From motionless clay to a soaring bird. I was something that was not able to move by itself and then I could fly in the sky. That is me."));
        books.add(new BookInformation("Muhammad Vandestra", 2017, "Kisah Hikayat Laba-Laba Gua Tsur Yang Mencintai & Melindungi Nabi Muhammad ", "AW Edisi Bilingual Inggris & Indonesia. Aku adalah laba-laba yang lebih tinggi dari pada laba-laba lainnya. Dengan segala kerendahan hati, jika semua laba-laba di dunia ini diletakkan di satu tangan dan aku dimasukkan ke tangan yang lain, aku akan melampaui keunggulan mereka. Aku bukan orang yang membuat klaim palsu dan pamer, aku hanya menyatakan fakta. Aku tidak berpikir bahwa aku perlu mengenalkan diri aku kepada pembaca, karena aku yakin Anda mengerti bahwa aku adalah laba-laba dari gua yang diutus Allah oleh Rasulullah saw bersembunyi. Akulah yang bertanggung jawab untuk pembebasan Nabi. Akulah yang diutus Allah untuk melindunginya."));
        books.add(new BookInformation("Samantha Kuk", 2017, "Vortigern's Garden", "In the Glade, a town tucked away within a wall of unending blackberry thorns, people receive the magic ability to grow and wither plants at will. A plucky teenager by the name of Niss is gifted with the talent to grow untold amounts of flowers at the flick of her wrist — something unprecedented within her community."));
        books.add(new BookInformation("Marissa Meyer", 2016, "Heartless", "Catherine may be one of the most desired girls in Wonderland and a favorite of the unmarried King, but her interests lie elsewhere. A talented baker, she wants to open a shop and create delectable pastries. But for her mother, such a goal is unthinkable for a woman who could be a queen. At a royal ball where Cath is expected to receive the King's marriage proposal, she meets handsome and mysterious Jest. For the first time, she feels the pull of true attraction. At the risk of offending the King and infuriating her parents, she and Jest enter into a secret courtship. Cath is determined to choose her own destiny. But in a land thriving with magic, madness, and monsters, fate has other plans."));
        books.add(new BookInformation("J D Rinehart", 2016, "The lost realm", "Triplets, Tarlan, Elodie, and Gulph, are no closer to finding each other or gaining the throne. But as the threats to their existence grow, so do their powers. Can the three survive, fulfill the prophecy, and bring peace to the land? Or will they meet an untimely fate?"));
        books.add(new BookInformation("Mercedes Lackey", 2016, "A study in sable", "Sent by Lord Alderscroft to the bachelor's flat of a certain famous, and rather rude, detective, psychics Sarah and Nan are compelled to prove their powers to him before being asked to consult on behalf of his Elemental Masters associates, John and Mary Watson."));
        books.add(new BookInformation("Janette Rallison", 2016, "The wrong side of magic", "Eighth-grader Hudson stopped believing in magic long ago. Until the day he is whisked away to the magical land of Logos--a land ruled by words, thoughts, and memories. Upon arrival, Hudson is quickly saddled with a troll curse, and only his friend Charlotte can help rid him of the curse. But she has an agenda of her own--find and rescue the missing Princess of Logos"));
        books.add(new BookInformation("Constance Cooper", 2016, "Guile", "In the Bad Bayous, guile--a power in the water that changes people and objects, sometimes for the worse--sets Yonie Watereye, 16, on a path that puts her own life in danger as she traces her family tree and finds a murderer"));
        books.add(new BookInformation("Adam Shaughnessy", 2016, "Over the underworld", "It's been a year since friends ABE and Pru joined Mister Fox's Fantasy Investigation Bureau--otherwise known as the Unbelievable FIB. In their next adventure, they must outrun trolls, explore Asgard and the Viking underworld, and try to outsmart the Queen of the Dead herself to change fate, save the world--and survive seventh grade"));
        books.add(new BookInformation("Dianne K Salerni", 2016, "The Morrigan's curse", "The battle between Kin and Transitioners that's been brewing for centuries has finally come to a head. The sinister Kin have captured Evangeline's younger sister, Addie, a descendant of Merlin whose presence will allow them to reverse the Eighth Day Spell and free themselves. Addie doesn't realize the full consequences of her cooperation. She's been helping the Kin because they value the strength of her magi--something Evangeline never did. The feeling of power coursing through her veins is impossible to resist. Meanwhile, Riley, Evangeline, and Jax craft a plan to rescue Addie from her captors. But the Kin's unstoppable magic, and a rebellious Addie, force Riley to reconsider whether saving Addie is worth sacrificing everyone who lives in the seven-day week. Jax won't let Evangeline's sister be used as a pawn, so he risks it all in a secret mission of his own. With the Morrigan pushing both sides of the war toward annihilation, Addie must decide where her loyalties lie, while Jax, Riley, and Evangeline confront the possibility of losing Addie to save the world."));
        books.add(new BookInformation("Pat Esden", 2016, "Beyond your touch", "She wants more than he can promise. His desires could lead to betrayal. But without each other, neither can survive the dangers ahead. Annie Freemont knows this isn't the right time to get involved with a man like Chase. After years of distrust, she's finally drawing close to her estranged family, and he's an employee on their estate in Maine. Though she never intended to stay on the estate for long, her father's illness and the mysteries surrounding her family made leaving impossible. And now with the newfound hope of rescuing her long-missing mother, Annie's determined to be involved with the family's plans one way or another. If only she could keep her mind off Chase and focus on the impending rescue. But there's something about the enigmatic Chase that she can't resist. And she's not the only woman. Annie fears a seductive stranger who is key to safely freeing her mother is also obsessed with him. As plans transform into action and time for a treacherous journey into a strange world draws near, every move Annie makes will test the one bond she's trusted with her secrets, her desires--and her heart."));
        books.add(new BookInformation("Margaret Dilloway", 2016, "Xander and the Lost Island of Monsters", "Twelve-year-old Xander discovers and learns to use the fantastic powers that are his birthright in order to save his father. Based on Japanese mythology."));
        books.add(new BookInformation("Kristy Logan", 2015, "The gracekeepers", "A lyrical and moving debut in the tradition of Angela Carter and Margaret Atwood, introducing an original and commanding new voice in fiction As a Gracekeeper, Callanish administers shoreside burials, laying the dead to their final resting place deep in the depths of the ocean. Alone on her island, she has exiled herself to a life of tending watery graves as penance for a long-ago mistake that still haunts her. Meanwhile, North works as a circus performer with the Excalibur, a floating troupe of acrobats, clowns, dancers, and trainers who sail from one archipelago to the next, entertaining in exchange for sustenance. In a world divided between those inhabiting the mainland (\"landlockers\") and those who float on the sea (\"damplings\"), loneliness has become a way of life for North and Callanish, until a sudden storm offshore brings change to both their lives--offering them a new understanding of the world they live in and the consequences of the past, while restoring hope in an unexpected future. Inspired in part by Scottish myths and fairytales, The Gracekeepers tells a modern story of an irreparably changed world: one that harbors the same isolation and sadness, but also joys and marvels of our own age."));
        books.add(new BookInformation("John Christopher", 2015, "Fireball", "When Simon and Brad investigate the mysterious fireball, they suddenly find themselves in an alternate world--a world where the unrealized possibilities of the actual world have been realized."));
        books.add(new BookInformation("Marci Jefferson", 2015, "Enchantress of Paris", "The alignment of the stars at Marie Mancini's birth warned that although she would be gifted at divination, she was destined to disgrace her family. Nonetheless, Cardinal Mazarin brings his niece to the opulent French court, where the forbidden occult arts thrive in secret. In France, Marie discovers that her powerful uncle rules, using Marie's sister Olympia to hold the Sun King, Louis XIV, in thrall. Desperate to avoid her mother's dying wish that she spend her life in a convent, Marie burns her grimoire, trading Italian superstitions for polite sophistication. As her star rises, King Louis becomes enchanted by Marie's charm. Sensing a chance to grab even greater power, Cardinal Mazarin pits the sisters against each other, showering Marie with diamonds and silks in exchange for bending King Louis to his will. Disgusted by Mazarin's ruthlessness, Marie rebels. She sacrifices everything, but exposing Mazarin's darkest secret threatens to tear France apart. When even King Louis' love fails to protect Marie, she must summon her powers of divination. Fraught with conspiracy and passion, Enchantress of Paris is a captivating historical novel about a woman whose love was more powerful than magic"));
        books.add(new BookInformation("Michael R Jensen", 2015, "Woven", "A princess and a ghost set out on a journey to find a magic needle that can sew the ghost back to his life."));
        books.add(new BookInformation("Dean Ray Koontz", 2015, "Saint Odd", "From \"one of the master storytellers of this or any age\" (The Tampa Tribune) comes the stunning final adventure of \"one of the most remarkable and appealing characters in current fiction\"(The Virginian-Pilot)--as #1 New York Times bestselling author Dean Koontz brings the unforgettable odyssey of Odd Thomas to its dazzling conclusion. Odd Thomas is back where it all started. because the time has come to finish it. Since he left his simple life in the small town of Pico Mundo, California, his journey has taken him to places strange and wonderful, mysterious and terrifying. Across the land, in the company of mortals and spirits alike, he has known kindness and cruelty, felt love and loss, saved lives and taken them--as he's borne witness to humanity's greatest good and darkest evil. Again and again, he has gone where he must and done what he had to do--for better or worse--with his courage and devotion sorely tested, and his soul forever changed. Every triumph has been hard won. Each sacrifice has taken its toll. Now, whatever destiny drives him has finally steered his steps home, where those he cares for most surround him, the memory of his tragically lost true love haunts him, and one last challenge--vast and dreadful--awaits him. For Odd Thomas, born to serve a purpose far greater than himself, the wandering is done. Only the reckoning remains. Acclaim for Dean Koontz and his Odd Thomas novels \"Odd's strange gifts, coupled with his intelligence and self-effacing humor, make him one of the most quietly authoritative characters in recent popular fiction.\"--Publishers Weekly \"Koontz gives his character wit, good humor, a familiarity with the dark side of humanity--and moral outrage.\"--USA Today \"The ultimate Everyman. an avatar of hope and honor and courage for all of us--the linchpin of a rollicking good tale. Odd evokes the homespun wisdom of Forrest Gump amid the mind-spinning adventures of a Jack Bauer."));
        books.add(new BookInformation("Daisy Meadows", 2015, "Alexa, el hada reportera de moda", "Ser reportera de moda es un trabajo importante, pero no si la moda es un desastre. Alexa, el hada reportera de moda, ha perdido su pluma mágica. ¿Podrán las chicas ayudarla?"));
        books.add(new BookInformation("Daisy Meadows", 2015, "Jennifer, el hada estilista", "Sin el cepillo mágico de Jennifer, el hada estilista, ¡todos andan con el cabello desarreglado! ¿Podrán Raquel y Cristina salvar la situación?"));
        books.add(new BookInformation("Jeanna Kunce", 2015, "Darien and the seed of obreget", "A young girl named Darien uses magic paints to travel to another world and goes on a quest to retrieve a seed from the Tree of Healing."));
        // @formatter:on
    }

    public void printList() {
        var sorted = sort.sort(books);
        for (var book : sorted)
            System.out.println(book);
    }

    public void setSorter(BookSorter sorter) {
        sort = sorter;
    }
}
